// Generated by AI based on https://docs.anthropic.com/en/api/messages
package claude

type MessagesRequest struct {
	Model         string            `json:"model"`
	Messages      []*MessageContent `json:"messages"`
	MaxTokens     int64             `json:"max_tokens"`
	Metadata      Metadata          `json:"metadata,omitempty"`
	StopSequences []string          `json:"stop_sequences,omitempty"`
	Stream        bool              `json:"stream,omitempty"`
	System        string            `json:"system,omitempty"`
	Temperature   float64           `json:"temperature,omitempty"`
	ToolChoice    ToolChoice        `json:"tool_choice,omitempty"`
	TopK          int64             `json:"top_k,omitempty"`
	TopP          float64           `json:"top_p,omitempty"`
}

type MessageContent struct {
	Role    string `json:"role"`
	Content string `json:"content"`
}

type Source struct {
	Type      string `json:"type"`
	MediaType string `json:"media_type"`
	Data      string `json:"data"`
}

type Metadata struct {
	UserID string `json:"user_id,omitempty"`
}

type ToolChoice struct {
	Tools []Tool `json:"tools,omitempty"`
}

type Tool struct {
	Name        string      `json:"name"`
	Description string      `json:"description,omitempty"`
	InputSchema InputSchema `json:"input_schema"`
}

type InputSchema struct {
	Type       string            `json:"type"`
	Properties map[string]Schema `json:"properties"`
	Required   []string          `json:"required"`
}

type Schema struct {
	Type        string `json:"type"`
	Description string `json:"description,omitempty"`
}

type MessagesResponse struct {
	ID           string         `json:"id"`
	Type         string         `json:"type"`
	Role         string         `json:"role"`
	Content      []ContentBlock `json:"content"`
	Model        string         `json:"model"`
	StopReason   string         `json:"stop_reason,omitempty"`
	StopSequence string         `json:"stop_sequence,omitempty"`
	Usage        Usage          `json:"usage"`
}

type ContentBlock struct {
	Type string `json:"type"`
	Text string `json:"text,omitempty"`
}

type Usage struct {
	InputTokens              int64 `json:"input_tokens"`
	OutputTokens             int64 `json:"output_tokens"`
	CacheCreationInputTokens int64 `json:"cache_creation_input_tokens,omitempty"`
	CacheReadInputTokens     int64 `json:"cache_read_input_tokens,omitempty"`
}
