// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: web-settings.sql

package sqlc

import (
	"context"
)

const getWebSettings = `-- name: GetWebSettings :one
SELECT dark_mode, initted FROM web_settings LIMIT 1
`

func (q *Queries) GetWebSettings(ctx context.Context) (WebSetting, error) {
	row := q.db.QueryRowContext(ctx, getWebSettings)
	var i WebSetting
	err := row.Scan(&i.DarkMode, &i.Initted)
	return i, err
}

const updateWebSettings = `-- name: UpdateWebSettings :exec
UPDATE web_settings SET dark_mode = ?, initted = ?
`

type UpdateWebSettingsParams struct {
	DarkMode bool `json:"dark_mode"`
	Initted  bool `json:"initted"`
}

func (q *Queries) UpdateWebSettings(ctx context.Context, arg UpdateWebSettingsParams) error {
	_, err := q.db.ExecContext(ctx, updateWebSettings, arg.DarkMode, arg.Initted)
	return err
}
